
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "RNVideoFramesSpec.h"

namespace facebook::react {

static facebook::jsi::Value __hostFunction_NativeVideoFramesSpecJSI_extractFrames(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "extractFrames", "(Ljava/lang/String;Lcom/facebook/react/bridge/ReadableArray;Lcom/facebook/react/bridge/ReadableMap;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}

NativeVideoFramesSpecJSI::NativeVideoFramesSpecJSI(const JavaTurboModule::InitParams &params)
  : JavaTurboModule(params) {
  methodMap_["extractFrames"] = MethodMetadata {3, __hostFunction_NativeVideoFramesSpecJSI_extractFrames};
}

std::shared_ptr<TurboModule> RNVideoFramesSpec_ModuleProvider(const std::string &moduleName, const JavaTurboModule::InitParams &params) {
  if (moduleName == "NativeVideoFramesModule") {
    return std::make_shared<NativeVideoFramesSpecJSI>(params);
  }
  return nullptr;
}

} // namespace facebook::react
